FROM cimg/node:22.21.1


# LABEL name="Angular dev environment" \
#       description="This image can be used to create a dev environment for building Angular." \
#       vendor="angular" \
#       version="1.0"

EXPOSE 4000 4433 5000 8080 9876


# Switch to `root`.
USER root


# Go! (And keep going.)
CMD ["tail", "--follow", "/dev/null"]
